### ISSUE TITLE
File name too long error

### ISSUE THREAD

**Issue by nbthinkful** [Piasy/OkBuck#60]
Hi,

I'm testing buck on a multi-module project where I'm implementing a micro-service aproach for a system I'm writing.  I've configured okbuck 0.4.10 for my build but when I start to launch it, I get the following error, possibly because it's trying to create a file with concatenated dependency names: -

> /Users/nebo/dev/stash/obg2/.okbuck/common_deps/_authentication_ui__common_core__app_phoenix__global_ui__authentication_client__content_ui__common_ioc__app_sverigeautomaten__authentication_service__whitelabel_wrapper__common_ui__global_test__content_service__global_core__app_norgesautomaten__content_client_/BUCK (File name too long)

The okbuck configuration I'm using is the following: -

okbuck {
    target "android-23"
    signConfigName "release"
    overwrite true
    resPackages = [
            'App.Phoenix': 'com.phoenix',
            'App.Norgesautomaten': 'com.norgesautomaten',
            'App.Sverigeautomaten': 'com.sverigeautomaten',
            'Global.Core': 'obg.global.core',
            'Global.Ui': 'obg.global.ui',
            'Global.Test': 'obg.global.test',
            'Common.Core': 'obg.common.core',
            'Common.Ui': 'obg.common.ui',
            'Common.IoC': 'obg.common.ioc',
            'Authentication.Client': 'obg.authentication.ioc',
            'Authentication.Service': 'obg.authentication.ioc',
            'Authentication.Ui': 'obg.authentication.ioc',
            'Content.Client': 'obg.content.client',
            'Content.Service': 'obg.content.service',
            'Content.Ui': 'obg.content.ui'
    ]
}

**Comment by Piasy** [comment]
Oh, that's because you have some dependencies shared by too much module.

From log you provided, modules are: Authentication.Ui, Common.Core, App.Phoenix, Global.Ui, Authentication.Client... and because OkBuck will create a directory to put these shared dependencies, with all modules name concatenated, in such case, the directory will have a super long name which cause the error.

Now I'm rewriting OkBuck for version 1.0, and I don't want to do too much modification on current version, so my fix may come after a week or two.

Sorry about that :(

**Comment by Piasy** [comment]
@nbthinkful Hi, I just release v1.0.0-beta3, which solve this problem, please try it out!

**Comment by nbonavia** [comment]
Tested and I confirm that it solved the problem. I am looking forward for buck to support android databinding so that I can utilise okbuck - buck to the full. Well done, you've done a great job.
